### ISSUE TITLE
Default first BottomBarItem

### ISSUE THREAD

**Issue by jvillavicenciot26** [Mindinventory/animated_notch_bottom_bar#10]
How can I set a default BottomBarItem?

**Comment by jignesh-mind** [comment]
final _controller = NotchBottomBarController(index: 0);
 
![Screenshot 2023-05-26 at 11 49 27 AM](https://github.com/Mindinventory/animated_notch_bottom_bar/assets/112058958/f3cd1a07-b296-44f9-a00a-6a424ea4d658)


You can directly provide it to the your _controller.
Please check in the latest version.
