### ISSUE TITLE
Expected a value of type 'JavaScriptObject', but got one of type 'Null' Error for web?

### ISSUE THREAD

**Issue by Oliver84** [Mindinventory/animated_notch_bottom_bar#12]
I've got no problem getting this to work on mobile, but when I try to run it in web, I get this error:

The following TypeErrorImpl was thrown building AnimatedBuilder(animation:
AnimationController#d6079(⏮ 0.000; paused), dirty, state: _AnimatedState#24b94):
Expected a value of type 'JavaScriptObject', but got one of type 'Null'
The relevant error-causing widget was:
  AnimatedNotchBottomBar

**Comment by jignesh-mind** [comment]
Hello @Oliver84,
It would be helpful if you can share  minimal code to regenerate this issue as I'm unable to regenerate it.
