### ISSUE TITLE
remove right-bottom and left bottom radius

### ISSUE THREAD

**Issue by maliatli** [Mindinventory/animated_notch_bottom_bar#15]
First of all, thanks for widget.

How can I remove right-bottom and left-bottom corners radius?

![image](https://github.com/Mindinventory/animated_notch_bottom_bar/assets/11739279/f3e508b5-29cd-414e-8d54-2bdbbc908db4)

**Comment by Shilpa26v** [comment]
@maliatli 
Did you find a solution for this?

**Comment by thenicekat** [comment]
You can edit the library directly, by editing the lib/constants.dart file

**Comment by mi-raj04** [comment]
@maliatli we implement this functionality in animated_notch_bottom_bar: ^1.0.1
