### ISSUE TITLE
Can showShadow be separated from roundedEdges?

### ISSUE THREAD

**Issue by obumnwabude** [Mindinventory/animated_notch_bottom_bar#16]
Currently, when showShadow is set to true, the bottom left and bottom right sides are rounded and the shadow shows.

Is it possible to have another property for roundedEdges or for the borderRadius of each edge, while keeping the showShadow (or permitting its customisation)?

So that one can have the shadow without the roundedEdges.

**Comment by mi-raj04** [comment]
@obumnwabude  we implement this functionality in animated_notch_bottom_bar: ^1.0.1 version feel free to open issues if need help
