### ISSUE TITLE
Can i remove the navbar from another page that's not listed in the bottomBarPages list

### ISSUE THREAD

**Issue by christianoSinaga** [Mindinventory/animated_notch_bottom_bar#18]

**Comment by jignesh-mind** [comment]
Hello @christianoSinaga,
It would be helpful if you provide some description or more clear explanation.

**Comment by mi-raj04** [comment]
Hello @christianoSinaga 
As we haven't received any further input, we are closing this issue. Feel free to reach out to us for any additional assistance or if you have further questions. We are here to help.
