### ISSUE TITLE
Smaller height

### ISSUE THREAD

**Issue by HAdamCode** [Mindinventory/animated_notch_bottom_bar#30]
Hello. Love this component but it takes up just a little too much space. I tried to adjust the height and it seemed to not want to go below 62. I also changed icon sizes to see if maybe that would allow the height to change but to no avail. Is there something specific I need to do? Or is that feature just not available at this time?

Thanks for your help!

**Comment by jaydeepkaria-mi** [comment]
Hello @HAdamCode,

Thank you for your feedback. We have not added the functionality required to adjust the height below 62 due to specific UI requirements. We appreciate your understanding and will keep your suggestion in mind for future updates.

Thanks for your patience!

Best regards.

**Comment by mohit-chauhan-mi** [comment]
We'll let you know once we have any updates on this point.
