### ISSUE TITLE
Active item tap hitbox too small

### ISSUE THREAD

**Issue by talhabw** [Mindinventory/animated_notch_bottom_bar#31]
Taps on the active item are only triggered when tapped exactly on the icon, while there is a bigger hitbox for inactive items. Whole bubble should trigger the onTap in my opinion. 

Example photos from the widget inspector: 

Inactive Item:
![image](https://github.com/Mindinventory/animated_notch_bottom_bar/assets/56639619/05d96ce9-8780-48b6-9028-4aed2be7aa8d)
Active Item:
![image](https://github.com/Mindinventory/animated_notch_bottom_bar/assets/56639619/46e68687-d8c8-4ec9-8a3a-3697c71513df)

**Comment by mohit-chauhan-mi** [comment]
@talhabw We've implemented the current solution accordingly, due to the specific UI requirements. However, we appreciate your suggestion and will consider it for future updates. Thank you for your input.
