### ISSUE TITLE
Make bottom bar persistent

### ISSUE THREAD

**Issue by ptesting007** [Mindinventory/animated_notch_bottom_bar#35]
I want to add BottomBar persistent to every page while navigation to sub child or any page. Is it possible to add bottom bar persistent to every page? I am using GetX for navigation from one page to other.

**Comment by Manish8156** [comment]
@ptesting007, it is difficult for me to understand what you want based on your comment. Can you please provide a design or diagram of what you are trying to achieve?

**Comment by mohit-chauhan-mi** [comment]
Closing this issue for now. Please reopen it with more details if needed.
