### ISSUE TITLE
Functionality to use the widget without the dependency of the pageview

### ISSUE THREAD

**Issue by Danny-Rufus** [Mindinventory/animated_notch_bottom_bar#6]
As the title says is there a way to use the AnimatedNotchBottomBar without the use PageView?
Since the user can tend to use different widget to render the body of the scaffold.

**Comment by jignesh-mind** [comment]
Hello,
We have added this feature in **animated_notch_bottom_bar**: 1.0.0. Now you can use it without PageView by providing   **NotchBottomBarController**.
