### ISSUE TITLE
right to left align dosent work when use locale: const Locale('fa', 'IR'),

### ISSUE THREAD

**Issue by elhamChatrabnoos** [Mindinventory/animated_notch_bottom_bar#7]
Hi 
i use locale: const Locale('fa', 'IR'), in my code but 
the direction of bottim navigation dosent change when scroll its pages.

**Comment by jignesh-mind** [comment]
Hi @elhamChatrabnoos 
Please provide any screenshot or more details on what exactly you are asking for.
