### ISSUE TITLE
Functionality to limit the width of AnimatedNotchBottomBar for wider screens like macOS, web, tabs, etc

### ISSUE THREAD

**Issue by nitinjaiman** [Mindinventory/animated_notch_bottom_bar#8]
Functionality to limit the width of AnimatedNotchBottomBar for wider screens like macOS, web, tabs, etc. Current the width of AnimatedNotchBottomBar is based on screen size and for wide screens it takes away the whole screen and looks not asthetically pleasing. 

Current look on wide screens: https://ibb.co/d7VKd03

[![name](https://i.ibb.co/7bZywJT/Screenshot-2023-03-21-at-5-48-44-PM.png)](Current look on wide screens)

**Comment by jignesh-mind** [comment]
Hello,
We have added this feature in **animated_notch_bottom_bar**: 1.0.0. Now you can set **bottomBarWidth** for wider screens like web.
