### ISSUE TITLE
Functionality to use it upside down for tabbar

### ISSUE THREAD

**Issue by mustafa-fahimi** [Mindinventory/animated_notch_bottom_bar#9]
Please make it possible to use it as a tabbar but upside down. I know that I can do it with Flip or Rotation but having this inside the package will make it cooler. Thanks

**Comment by jignesh-mind** [comment]
@Tokenizer94 We will keep it in our todo and update the package. Thanks for the suggestion.

**Comment by mustafa-fahimi** [comment]
This is not fixed yet. Why it is closed? Will be an update any soon?

**Comment by jignesh-mind** [comment]
This is a functionality request which we are not planning any soon. Any PR will be welcome.
Thanks!
